In [1]:
import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("/work/Animal Shelter Data/2023ShelterReport.csv")

# Display basic information
print(df.info())  # Check data types and missing values
print(df.head())  # Preview first few rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   CALENDAR YEAR             777 non-null    int64
 1   LIC #                     777 non-null    int64
 2   COUNTY                    777 non-null    object
 3   FACILITY NAME             777 non-null    object
 4   SPECIES                   701 non-null    object
 5   INTAKE                    701 non-null    float64
 6   ADOPTED OUT               701 non-null    float64
 7   RETURNED TO OWNER         701 non-null    float64
 8   EUTHANIZED                700 non-null    float64
 9   TOTAL OPERATING EXPENSES  76 non-null     object
 10  COST PER ANIMAL           72 non-null     object
dtypes: float64(4), int64(2), object(5)
memory usage: 66.9+ KB
None
   CALENDAR YEAR  LIC #    COUNTY               FACILITY NAME  SPECIES  \
0           2023     23  ALAMANCE  BURLINGTON ANIMAL SERVICES      DOG
1           2023     23  ALAMANCE  BURLINGTON ANIMAL SERVICES      CAT
2           2023     23  ALAMANCE  BURLINGTON ANIMAL SERVICES      BAT
3           2023     23  ALAMANCE  BURLINGTON ANIMAL SERVICES  CHICKEN
4           2023     23  ALAMANCE  BURLINGTON ANIMAL SERVICES   CONURE

   INTAKE  ADOPTED OUT  RETURNED TO OWNER  EUTHANIZED  \
0  2190.0       1620.0              393.0       173.0
1  3987.0       3653.0               49.0       171.0
2     9.0          0.0                0.0         8.0
3    10.0         10.0                0.0         0.0
4     1.0          1.0                0.0         0.0

  TOTAL OPERATING EXPENSES COST PER ANIMAL
0                      NaN             NaN
1                      NaN             NaN
2                      NaN             NaN
3                      NaN             NaN
4                      NaN             NaN

In [2]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print(df.columns)  # Verify new column names

Index(['calendar_year', 'lic_#', 'county', 'facility_name', 'species',
       'intake', 'adopted_out', 'returned_to_owner', 'euthanized',
       'total_operating_expenses', 'cost_per_animal'],
      dtype='object')

In [3]:
# Convert species column to uppercase for consistency, then filter
df['species'] = df['species'].str.upper()  # Standardize as uppercase

df['species'] = df['species'].replace({'KITTENS (UNDER 6 MO)': 'CAT', 'PUPPIES (UNDER 6 MO)': 'DOG'})

In [4]:
'''# Convert expenses and cost to numeric, forcing errors to NaN
df["total_operating_expenses"] = pd.to_numeric(df["total_operating_expenses"].str.replace("$", "").str.replace(",", ""), errors='coerce')
df["cost_per_animal"] = pd.to_numeric(df["cost_per_animal"].str.replace("$", "").str.replace(",", ""), errors='coerce')

# Forward fill the values based on 'CALENDAR YEAR', 'LIC #', 'COUNTY', 'FACILITY NAME'
df[["total_operating_expenses", "cost_per_animal"]] = df.groupby(["CALENDAR YEAR", "LIC #", "COUNTY", "FACILITY NAME"])[["total_operating_expenses", "cost_per_animal"]].ffill()'''

'# Convert expenses and cost to numeric, forcing errors to NaN\ndf["total_operating_expenses"] = pd.to_numeric(df["total_operating_expenses"].str.replace("$", "").str.replace(",", ""), errors=\'coerce\')\ndf["cost_per_animal"] = pd.to_numeric(df["cost_per_animal"].str.replace("$", "").str.replace(",", ""), errors=\'coerce\')\n\n# Forward fill the values based on \'CALENDAR YEAR\', \'LIC #\', \'COUNTY\', \'FACILITY NAME\'\ndf[["total_operating_expenses", "cost_per_animal"]] = df.groupby(["CALENDAR YEAR", "LIC #", "COUNTY", "FACILITY NAME"])[["total_operating_expenses", "cost_per_animal"]].ffill()'

In [5]:
df = df[df['species'].isin(['DOG', 'CAT'])]

print(df['species'].value_counts())  # Check count of remaining species

#Drop 'total_operating_expenses' and 'cost_per_animal' due to high missing values
df = df.drop(columns=['total_operating_expenses', 'cost_per_animal'])

# Reset index
df = df.reset_index(drop=True)

species
DOG    76
CAT    76
Name: count, dtype: int64

In [6]:
print(df['species'].value_counts())  # Check count of remaining species

print(df.info())  # Check data again after cleaning

species
DOG    76
CAT    76
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   calendar_year      152 non-null    int64
 1   lic_#              152 non-null    int64
 2   county             152 non-null    object
 3   facility_name      152 non-null    object
 4   species            152 non-null    object
 5   intake             152 non-null    float64
 6   adopted_out        152 non-null    float64
 7   returned_to_owner  152 non-null    float64
 8   euthanized         151 non-null    float64
dtypes: float64(4), int64(2), object(3)
memory usage: 10.8+ KB
None

In [7]:
df = df.drop(columns=['calendar_year'])

In [8]:
df.head(15)

,lic_#,county,facility_name,species,intake,adopted_out,returned_to_owner,euthanized
0,23,ALAMANCE,BURLINGTON ANIMAL SERVICES,DOG,2190.0,1620.0,393.0,173.0
1,23,ALAMANCE,BURLINGTON ANIMAL SERVICES,CAT,3987.0,3653.0,49.0,171.0
2,74,ALEXANDER,ALEXANDER COUNTY ANIMAL SERVICES,DOG,288.0,134.0,94.0,53.0
3,74,ALEXANDER,ALEXANDER COUNTY ANIMAL SERVICES,CAT,267.0,131.0,6.0,113.0
4,43,ANSON,ANSON COUNTY ANIMAL SHELTER,DOG,663.0,613.0,42.0,5.0
5,43,ANSON,ANSON COUNTY ANIMAL SHELTER,CAT,206.0,172.0,2.0,0.0
6,79,ASHE,ASHE COUNTY ANIMAL CONTROL,DOG,480.0,363.0,105.0,12.0
7,79,ASHE,ASHE COUNTY ANIMAL CONTROL,CAT,564.0,535.0,12.0,17.0
8,58,BEAUFORT,BETSY BAILEY NELSON ANIMAL CONTROL FAC.,DOG,817.0,568.0,91.0,152.0
9,58,BEAUFORT,BETSY BAILEY NELSON ANIMAL CONTROL FAC.,CAT,836.0,516.0,8.0,287.0
10,126,BERTIE,"WINDSOR, TOWN OF",DOG,11.0,3.0,5.0,3.0
11,126,BERTIE,"WINDSOR, TOWN OF",CAT,6.0,5.0,1.0,0.0
12,85,BLADEN,BLADEN COUNTY ANIMAL SHELTER,DOG,893.0,695.0,119.0,51.0
13,85,BLADEN,BLADEN COUNTY ANIMAL SHELTER,CAT,684.0,533.0,12.0,146.0
14,15,BRUNSWICK,BRUNSWICK CO SHERIFF'S OFFICE APS,DOG,1881.0,797.0,372.0,597.0

In [9]:
df[df.isnull().any(axis=1)]

,lic_#,county,facility_name,species,intake,adopted_out,returned_to_owner,euthanized
82,121,MACON,MACON COUNTY ANIMAL SHELTER,CAT,632.0,21317.0,51.0,NaN

In [10]:
df['lic_#'] = df['lic_#'].astype(str)  # Convert License number to string

In [11]:
# Subtract "Returned to Owner" from "Intake"
df['adjusted_intake'] = df['intake'] - df['returned_to_owner']

#calculating the animals that remained in the shelter without getting adopted or euthanized
df['remaining_in_shelter'] = df['adjusted_intake'] - (df['adopted_out'] + df['euthanized'])

# Calculate the adoption rate (Adopted Out / Adjusted Intake)
df['adoption_rate'] = df['adopted_out'] / df['adjusted_intake']

# Calculate the adoption rate (euthanized / Adjusted Intake)
df['euthanasia_rate'] = df['euthanized'] / df['adjusted_intake']

# Calculating euthanasia rate and adoption rate and add columns
df['euthanasia_rate'] = (df['euthanized'] / df['intake']) * 100
df['adoption_rate'] = (df['adopted_out'] / df['intake']) * 100

In [12]:
df['remaining_in_shelter'] = df['remaining_in_shelter'].clip(lower=0)

negative_rows = df[df['remaining_in_shelter'] < 0]
print(negative_rows.shape[0], "rows have negative remaining counts.")

print(df)

0 rows have negative remaining counts.
    lic_#     county                     facility_name species  intake  \
0      23   ALAMANCE        BURLINGTON ANIMAL SERVICES     DOG  2190.0
1      23   ALAMANCE        BURLINGTON ANIMAL SERVICES     CAT  3987.0
2      74  ALEXANDER  ALEXANDER COUNTY ANIMAL SERVICES     DOG   288.0
3      74  ALEXANDER  ALEXANDER COUNTY ANIMAL SERVICES     CAT   267.0
4      43      ANSON       ANSON COUNTY ANIMAL SHELTER     DOG   663.0
..    ...        ...                               ...     ...     ...
147    19     WILKES     WILKES COUNTY ANIMAL SERVICES     CAT  2920.0
148   414     WILSON     WILSON COUNTY ANIMAL SERVICES     DOG  1223.0
149   414     WILSON     WILSON COUNTY ANIMAL SERVICES     CAT   849.0
150    46     YADKIN      YADKIN COUNTY ANIMAL SHELTER     DOG   277.0
151    46     YADKIN      YADKIN COUNTY ANIMAL SHELTER     CAT   619.0

     adopted_out  returned_to_owner  euthanized  adjusted_intake  \
0         1620.0              393.0       173.0           1797.0
1         3653.0               49.0       171.0           3938.0
2          134.0               94.0        53.0            194.0
3          131.0                6.0       113.0            261.0
4          613.0               42.0         5.0            621.0
..           ...                ...         ...              ...
147        746.0               26.0      2138.0           2894.0
148        641.0              284.0       302.0            939.0
149        278.0               12.0       548.0            837.0
150        121.0               63.0        80.0            214.0
151        447.0                8.0       165.0            611.0

     remaining_in_shelter  adoption_rate  euthanasia_rate
0                     4.0      73.972603         7.899543
1                   114.0      91.622774         4.288939
2                     7.0      46.527778        18.402778
3                    17.0      49.063670        42.322097
4                     3.0      92.458522         0.754148
..                    ...            ...              ...
147                  10.0      25.547945        73.219178
148                   0.0      52.412101        24.693377
149                  11.0      32.744405        64.546525
150                  13.0      43.682310        28.880866
151                   0.0      72.213247        26.655897

[152 rows x 12 columns]

In [13]:
df.head()

,lic_#,county,facility_name,species,intake,adopted_out,returned_to_owner,euthanized,adjusted_intake,remaining_in_shelter,adoption_rate,euthanasia_rate
0,23,ALAMANCE,BURLINGTON ANIMAL SERVICES,DOG,2190.0,1620.0,393.0,173.0,1797.0,4.0,73.972603,7.899543
1,23,ALAMANCE,BURLINGTON ANIMAL SERVICES,CAT,3987.0,3653.0,49.0,171.0,3938.0,114.0,91.622774,4.288939
2,74,ALEXANDER,ALEXANDER COUNTY ANIMAL SERVICES,DOG,288.0,134.0,94.0,53.0,194.0,7.0,46.527778,18.402778
3,74,ALEXANDER,ALEXANDER COUNTY ANIMAL SERVICES,CAT,267.0,131.0,6.0,113.0,261.0,17.0,49.063670,42.322097
4,43,ANSON,ANSON COUNTY ANIMAL SHELTER,DOG,663.0,613.0,42.0,5.0,621.0,3.0,92.458522,0.754148

In [14]:
null_values = df.isnull().sum()
print(null_values)

lic_#                   0
county                  0
facility_name           0
species                 0
intake                  0
adopted_out             0
returned_to_owner       0
euthanized              1
adjusted_intake         0
remaining_in_shelter    1
adoption_rate           4
euthanasia_rate         5
dtype: int64

In [15]:
# Remove rows with any null values
df = df.dropna(subset=['intake', 'adopted_out', 'euthanized', 'adopted_out'])

In [16]:
null_values = df.isnull().sum()
print(null_values)

lic_#                   0
county                  0
facility_name           0
species                 0
intake                  0
adopted_out             0
returned_to_owner       0
euthanized              0
adjusted_intake         0
remaining_in_shelter    0
adoption_rate           4
euthanasia_rate         4
dtype: int64

In [17]:
'''Q1 = df['euthanasia_rate'].quantile(0.25)
Q3 = df['euthanasia_rate'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(lower_bound, upper_bound)
outliers = df[(df['euthanasia_rate'] < lower_bound) | (df['euthanasia_rate'] > upper_bound)]
print(outliers)'''

"Q1 = df['euthanasia_rate'].quantile(0.25)\nQ3 = df['euthanasia_rate'].quantile(0.75)\nIQR = Q3 - Q1\nlower_bound = Q1 - 1.5 * IQR\nupper_bound = Q3 + 1.5 * IQR\nprint(lower_bound, upper_bound)\noutliers = df[(df['euthanasia_rate'] < lower_bound) | (df['euthanasia_rate'] > upper_bound)]\nprint(outliers)"

In [18]:
'''Q1 = df['adoption_rate'].quantile(0.25)
Q3 = df['adoption_rate'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['adoption_rate'] < lower_bound) | (df['adoption_rate'] > upper_bound)]
print(outliers)'''

"Q1 = df['adoption_rate'].quantile(0.25)\nQ3 = df['adoption_rate'].quantile(0.75)\nIQR = Q3 - Q1\nlower_bound = Q1 - 1.5 * IQR\nupper_bound = Q3 + 1.5 * IQR\noutliers = df[(df['adoption_rate'] < lower_bound) | (df['adoption_rate'] > upper_bound)]\nprint(outliers)"

In [19]:
# Group by county and calculate sums for relevant columns
grouped_df = df.groupby(['county'], as_index=False).agg({
    'intake': 'sum',
    'adjusted_intake': 'sum',
    'adopted_out': 'sum',
    'returned_to_owner': 'sum',
    'euthanized': 'sum', 
}).reset_index()

# Now, calculate the adoption rate and euthanasia rate per county
grouped_df['adoption_rate'] = (grouped_df['adopted_out'] / grouped_df['adjusted_intake']) * 100
grouped_df['euthanasia_rate'] = (grouped_df['euthanized'] / grouped_df['adjusted_intake']) * 100

grouped_df.drop(columns=['index'], inplace=True)
print(grouped_df)

       county  intake  adjusted_intake  adopted_out  returned_to_owner  \
0    ALAMANCE  6177.0           5735.0       5273.0              442.0
1   ALEXANDER   555.0            455.0        265.0              100.0
2       ANSON   869.0            825.0        785.0               44.0
3        ASHE  1044.0            927.0        898.0              117.0
4    BEAUFORT  1653.0           1554.0       1084.0               99.0
..        ...     ...              ...          ...                ...
59     WARREN  1051.0            979.0        763.0               72.0
60      WAYNE  3184.0           2940.0       1383.0              244.0
61     WILKES  4800.0           4580.0       1764.0              220.0
62     WILSON  2072.0           1776.0        919.0              296.0
63     YADKIN   896.0            825.0        568.0               71.0

    euthanized  adoption_rate  euthanasia_rate
0        344.0      91.944202         5.998256
1        166.0      58.241758        36.483516
2          5.0      95.151515         0.606061
3         29.0      96.871629         3.128371
4        439.0      69.755470        28.249678
..         ...            ...              ...
59       224.0      77.936670        22.880490
60      1253.0      47.040816        42.619048
61      2803.0      38.515284        61.200873
62       850.0      51.745495        47.860360
63       245.0      68.848485        29.696970

[64 rows x 8 columns]

In [20]:
# Save the cleaned dataset to a new CSV file
grouped_df.to_csv('species_combined.csv', index=False)

In [21]:
grouped_df.head()

,county,intake,adjusted_intake,adopted_out,returned_to_owner,euthanized,adoption_rate,euthanasia_rate
0,ALAMANCE,6177.0,5735.0,5273.0,442.0,344.0,91.944202,5.998256
1,ALEXANDER,555.0,455.0,265.0,100.0,166.0,58.241758,36.483516
2,ANSON,869.0,825.0,785.0,44.0,5.0,95.151515,0.606061
3,ASHE,1044.0,927.0,898.0,117.0,29.0,96.871629,3.128371
4,BEAUFORT,1653.0,1554.0,1084.0,99.0,439.0,69.755470,28.249678